spring:
  servlet:
    multipart:
      max-file-size: 3000KB
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: Adam1
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baselineOnMigrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: adam.111.testowy
    password: Test1234!
    properties:
      mail:
        smtp: #protokół do wysyłania maili
          ssl: #połączenie szyfrowane
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
file:
  product: C:\Users\adamb\OneDrive\Pulpit\ProductFileShop
